routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\TaxpayerController;
use App\Http\Controllers\DocumentTypeController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

/* Route::group(['middleware' => ['auth:admin']], function () {
    // Rutas protegidas para el guardia 'admin'
}); */


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('/user', RolesController::class)->except(['store', 'update']);
    Route::match(['post', 'put'], '/user', [RolesController::class, 'storeOrUpdate'])->name('user.storeOrUpdate');

    Route::resource('/taxpayer', TaxpayerController::class)->except(['store', 'update']);
    Route::match(['post', 'put'], '/taxpayer', [TaxpayerController::class, 'storeOrUpdate'])->name('taxpayer.storeOrUpdate');
    
    Route::resource('/document-type', DocumentTypeController::class);
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'lastname',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/users/form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            {{ __('user.users') }} / {{ (isset($user)) ? __('Edit') : __('Add') }}
        </h2>
    </x-slot>
    <section>
        <div class="py-6">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <div class="p-4 sm:p-8 bg-primary text-white shadow sm:rounded-lg container">

                    <header>
                        <h2 class="text-lg font-medium">
                            {{ __('user.info') }}
                        </h2>
                    </header>

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <hr>

                    @if(isset($user))
                    <form action="{{ route('user.storeOrUpdate', ['user' =>$user]) }}" method="POST"
                        class="mt-6 space-y-6">
                        @method('PUT')
                        @csrf
                        <input type="hidden" name="id" value="{{$user->id}}">
                    @else
                    <form action="{{ route('user.storeOrUpdate') }}" method="POST" class="mt-6 space-y-6">
                        @method('POST')
                        @csrf
                    @endif
                        <input type="hidden" id="read_only" value="{{$read_only ?? 'false' }}">

                        <div class="container">
                            <div class="row">
                                <div class="col-9">
                                    <div class="row">
                                        <!-- Name -->
                                        <div class="col-6">
                                            <x-input-label for="name" :value="__('Name')" />
                                            <x-text-input id="name" name="name" type="text"
                                                class="block mt-1 w-full"
                                                :value="isset($user) ? $user->name : (old('name') ?? '')"
                                                autofocus autocomplete="name" />
                                            <x-input-error :messages="$errors->get('name')" class="mt-2" />
                                        </div>

                                        <!-- Surnames -->
                                        <div class="col-6">
                                            <x-input-label for="lastname" :value="__('Lastname')" />
                                            <x-text-input id="lastname" name="lastname" type="text"
                                                class="block mt-1 w-full"
                                                :value="isset($user) ? $user->lastname: (old('lastname') ?? '')"
                                                autofocus autocomplete="lastname" />
                                            <x-input-error :messages="$errors->get('lastname')"
                                                class="mt-2" />
                                        </div>
                                    </div>

                                    <div class="row">
                                        <!-- Email Address -->
                                        <div class="col-12">
                                            <x-input-label for="email" :value="__('E-Mail Address')" />
                                            <x-text-input id="email" name="email" type="email"
                                                class="block mt-1 w-full"
                                                :value="isset($user) ? $user->email : (old('email') ?? '')"
                                                autocomplete="username" />
                                            <x-input-error :messages="$errors->get('email')" class="mt-2" />
                                        </div>
                                    </div>

                                    <div class="row">
                                        <!-- Password -->
                                        <div class="col-6">
                                            <x-input-label for="password" :value="__('Password')" />
                                            <x-text-input id="password" name="password" type="password"
                                                class="block mt-1 w-full"
                                                :value="isset($user) ? $user->password : (old('password') ?? '')"
                                                autocomplete="new-password" />
                                            <x-input-error :messages="$errors->get('password')"
                                                class="mt-2" />
                                        </div>

                                        <!-- Confirm Password -->
                                        <div class="col-6">
                                            <x-input-label for="password_confirmation"
                                                :value="__('Confirm Password')" />
                                            <x-text-input id="password_confirmation"
                                                name="password_confirmation" type="password"
                                                class="block mt-1 w-full"
                                                :value="isset($user) ? $user->password : (old('password') ?? '')"
                                                autocomplete="new-password" />
                                            <x-input-error :messages="$errors->get('password_confirmation')"
                                                class="mt-2" />
                                        </div>
                                    </div>
                                </div>
                                <div class="col-3 d-flex justify-content-center align-items-center">
                                    <div class="card">
                                        <div class="card-header">
                                            <h5>Roles</h5>
                                        </div>
                                        <div class="card-body">
                                            <p>SuperAdmin</p>
                                            <p>Admin</p>
                                            <p>Normal</p>
                                        </div>
                                        <div class="card-footer">
                                            EN PROCESO AÚN
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>


                        <div class="row">
                            <div class="flex items-center gap-4 justify-content-end">
                                <x-secondary-button onclick="history.back()" class="bg-light">
                                    {{ __('Cancel') }}
                                </x-secondary-button>

                                @if(!(isset($read_only) && $read_only))
                                <x-primary-button>
                                    @if (isset($taxpayer))
                                    {{ __('Update') }}
                                    @else
                                    {{ __('Save') }}
                                    @endif
                                </x-primary-button>
                                @endif

                                @if (session('status') === 'profile-updated')
                                <p x-data="{ show: true }" x-show="show" x-transition
                                    x-init="setTimeout(() => show = false, 2000)"
                                    class="text-sm text-gray-600 dark:text-gray-400">{{ __('Saved.') }}
                                </p>
                                @endif
                            </div>
                        </div>

                    </form>

                </div>
            </div>
        </div>
    </section>

    <x-slot name="script">
        @include('taxpayers.scripts-form')
    </x-slot>

</x-app-layout>

resources/views/users/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            {{ __('user.users') }}
        </h2>
    </x-slot>
    <section>
        <div class="py-12">
            <div class=" pt-3 max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <div class="p-4 sm:p-8 bg-primary text-white shadow sm:rounded-lg">
                    <header>
                        <h2 class="text-lg font-medium">
                            {{ __('user.users') }}
                        </h2>
    
                        {{--<!-- <p class="mt-1 text-sm">
                            {{ __("Update your account's profile information and email address.") }}
                        </p> -->--}}
                    </header>
                    @can('create user')
                    <div class="d-flex justify-content-end">
                        <x-link-button href="{{ route('user.create') }}">
                            {{ __('Add') }}
                        </x-link-button>
                    </div>
                    @endcan

                    <div class="py-6">
                        <input type="hidden" id="role" value="{{ Auth::user()->getRoleNames() }}" >
                        <hr>
                        <!-- <table -->
                        <!--   Tipo documento | Documento | Nombres | Apellidos -->
                        <table id="usersTable" class="table table-striped table-secondary" style="width:100%">
                            <thead>
                                <tr>
                                    <th> {{__('user.name')}} </th>
                                    <th> {{__('user.lastname')}} </th>
                                    <th> {{__('user.email')}} </th>
                                    <th> {{__('user.updated_at')}} </th>
                                    <th> {{__('Actions')}} </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                <tr>
                                    <td> {{ $user->name }} </td>
                                    <td> {{ $user->lastname }} </td>
                                    <td> {{ $user->email }} </td>
                                    <td> {{ date("d F Y : h m A", strtotime($user->updated_at)) }} </td>
                                    <td>
                                        <div class="d-flex justify-content-between align-items-center">
                                            @can('view doctype')
                                            <x-link-button href="{{ route('user.show', $user->id ) }}" class="pl-2">
                                                <x-see-svg/>                                          
                                            </x-link-button>
                                            @endcan
                                            @can('edit user')
                                            <x-link-button href="{{ route('user.edit', $user->id ) }}" class="pl-2">
                                                <x-edit-svg/>                                          
                                            </x-link-button>
                                            @endcan
                                            @can('delete user')
                                            <div class="btn p-0">
                                                <form method="POST"
                                                    action="{{ route('user.destroy', ['user' => $user]) }}"
                                                    class=""
                                                >
                                                    @csrf 
                                                    @method('DELETE')  
                                                    <x-danger-button type="submit">
                                                        <x-delete-svg/>
                                                    </x-danger-button>
                                                </form>
                                            </div>
                                            @endcan
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th> {{__('user.name')}} </th>
                                    <th> {{__('user.lastname')}} </th>
                                    <th> {{__('user.email')}} </th>
                                    <th> {{__('user.updated_at')}} </th>
                                    <th> Actions </th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </section>

    <x-slot name="script">
        @include('users.scripts-list')
    </x-slot>
</x-app-layout>

resources/views/users/scripts-form.blade.php
<script type="module" >

    $(document).ready(function () {
    if ($('#read_only').val() == true) {
        $('select').prop('disabled', true);
        //$('select').removeProp('required');
        $('input').prop('disabled', true);
        //$('input').remove('required');
        }
    });
    
</script>

resources/views/users/scripts-list.blade.php
<script type="module">
    $('#usersTable').DataTable({
        language,
        columns: [
            { data: "name", width: '10%' },
            { data: "lastname", width: '15%' },
            { data: "email", width: '20%' },
            { data: "updated_ad", width: '20%' },
            { data: "actions", width: '20%' },
        ],
    });

</script>