routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\TaxpayerController;
use App\Http\Controllers\DocumentTypeController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

/* Route::group(['middleware' => ['auth:admin']], function () {
    // Rutas protegidas para el guardia 'admin'
}); */


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('/user', RolesController::class)->except(['store', 'update']);
    Route::match(['post', 'put'], '/user', [RolesController::class, 'storeOrUpdate'])->name('user.storeOrUpdate');

    Route::resource('/taxpayer', TaxpayerController::class)->except(['store', 'update']);
    Route::match(['post', 'put'], '/taxpayer', [TaxpayerController::class, 'storeOrUpdate'])->name('taxpayer.storeOrUpdate');
    
    Route::resource('/document-type', DocumentTypeController::class);
});

require __DIR__.'/auth.php';

app/Models/Taxpayer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Taxpayer extends Model
{
    use HasFactory;

    public function documentType()
    {
        return $this->belongsTo(DocumentType::class, 'doc_type', 'short_name'); // Specify custom foreign and local key columns
        //return $this->belongsTo(DocumentType::class, 'short_name');
    }
}

app/Http/Controllers/TaxpayerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Taxpayer;
use App\Models\DocumentType;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Flash;
use Illuminate\Support\Facades\Validator;

class TaxpayerController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        return view('taxpayers.list')
            ->with('doctype', $this->getDocTypeSelect())
            ->with('taxpayers', Taxpayer::with('documentType')->get());
    }
    
    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('taxpayers.form')
                ->with('doctype', $this->getDocTypeSelect());
    }

    /**
     * Store a newly created resource in storage.
     */
    public function storeOrUpdate(Request $request)
    {
        try {
            $taxpayer = ($request->input('id')!='')
                        ? Taxpayer::find($request->input('id'))
                        : new Taxpayer();

            $validatedData = $request->validateWithBag('taxpayer', [
                'doc_type' => ['required', 'string', 'max:5'],
                'doc_number' => ['unique:taxpayers,doc_number,'. $request->input('id')],// Ensure unique document number except this record
                'names' => ['required', 'string', 'max:30'],
                'address' => ['string'],
                'phone' => ['nullable', 'string'],
                'email' => ['nullable', 'email'],
            ]);
            /* 
            doc_type doc_number names lastnames address phone phone secondary_phone email
            */
    
            $taxpayer->doc_type = $validatedData['doc_type'];
            $taxpayer->doc_number = $validatedData['doc_number'];
            $taxpayer->names = $validatedData['names'];
            $taxpayer->lastnames = $validatedData['lastnames'] ?? '';
            $taxpayer->address = $validatedData['address'];
            $taxpayer->phone = $validatedData['phone'];
            $taxpayer->email = $validatedData['email'];
    
            $taxpayer->save();
    
            return redirect()->route('taxpayer.index');
        } catch (\Throwable $th) {
            return back()->withErrors(['error' => $th->getMessage()]);
        }
    }


    /**
     * Display the specified resource.
     */
    public function show(Taxpayer $taxpayer)
    {
        return view('taxpayers.form')
            ->with('taxpayer', $taxpayer)
            ->with('doctype', $this->getDocTypeSelect())
            ->with('read_only', true);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Taxpayer $taxpayer)
    {
        return view('taxpayers.form')
            ->with('doctype', $this->getDocTypeSelect())
            ->with('taxpayer', $taxpayer);
    }

    /**
     * Update the specified resource in storage.
     */


    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Taxpayer $taxpayer)
    {
        $taxpayer->delete();
        return redirect()->route('taxpayer.index');
    }

    private function getDocTypeSelect() {
        $document_types = DocumentType::all();
        $document_types_select = [];
        foreach ($document_types as $document_type) {
            $document_types_select[$document_type->short_name] = $document_type->name;
        }
        return $document_types_select;
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/taxpayers/form.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            {{ __('taxpayers.taxpayers') }} / {{ (isset($taxpayer)) ? __('Edit') : __('Add') }}
        </h2>
    </x-slot>
    <section>
        <div class="py-6">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <div class="p-4 sm:p-8 bg-primary text-white shadow sm:rounded-lg container">

                    <header>
                        <h2 class="text-lg font-medium">
                            {{ __('taxpayers.info') }}
                        </h2>
                    </header>

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    
                    <hr>

                    @if(isset($taxpayer))
                        <form action="{{ route('taxpayer.storeOrUpdate', ['taxpayer' =>$taxpayer]) }}" method="POST"
                            class="mt-6 space-y-6">
                            @method('PUT')
                            @csrf
                            <input type="hidden" name="id" value="{{$taxpayer->id}}">
                    @else
                        <form action="{{ route('taxpayer.storeOrUpdate') }}" method="POST" class="mt-6 space-y-6">
                            @method('POST')
                            @csrf
                    @endif
                            <input type="hidden" id="read_only" value="{{$read_only ?? 'false'}}">

                            <div class="row">
                                <!-- docType -->
                                <div class="col-6">
                                    <x-input-label for="doc_type" :value="__('taxpayers.docType')" />
                                    <x-select-input :options="$doctype"
                                        :value="isset($taxpayer) ? $taxpayer->doc_type : (old('doc_type') ?? '')"
                                        id="doc_type" name="doc_type" class="mt-1 block w-full"
                                        required autofocus
                                        autocomplete="doc_type"></x-select-input>
                                </div>

                                <!-- docNumber -->
                                <div class="col-6">
                                    <x-input-label for="doc_number" :value="__('taxpayers.docNumber')" />
                                    <x-text-input id="doc_number" name="doc_number" type="text"
                                        class="mt-1 block w-full @error('title') is-invalid @enderror"
                                        :value="isset($taxpayer) ? $taxpayer->doc_number : (old('doc_number') ?? '')"
                                         required autofocus autocomplete="doc_number" />
                                    <x-input-error class="mt-2" :messages="$errors->get('doc_number')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- names -->
                                <div class="col-6" id="names_div">
                                    <x-input-label for="name" id="label_names" :value="__('taxpayers.names')" />
                                    <x-text-input id="names" name="names" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->names : (old('names') ?? '')"
                                         required autofocus autocomplete="names" />
                                    <x-input-error class="mt-2" :messages="$errors->get('names')" />
                                </div>

                                <!-- lastnames -->
                                <div class="col-6">
                                    <x-input-label for="lastnames" id="label_lastnames" :value="__('taxpayers.lastnames')" />
                                    <x-text-input id="lastnames" name="lastnames" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->lastnames : (old('lastnames') ?? '')"
                                         autofocus autocomplete="lastnames" />
                                    <x-input-error class="mt-2" :messages="$errors->get('lastnames')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- address -->
                                <div class="col-12">
                                    <x-input-label for="address" :value="__('taxpayers.address')" />
                                    <x-text-input id="address" name="address" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->address : (old('address') ?? '')" 
                                         required autofocus autocomplete="address" />
                                    <x-input-error class="mt-2" :messages="$errors->get('address')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- phone -->
                                <div class="col-6">
                                    <x-input-label for="phone" :value="__('taxpayers.phone')" />
                                    <x-text-input id="phone" name="phone" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->phone : (old('phone') ?? '')"
                                         required autofocus autocomplete="phone" />
                                    <x-input-error class="mt-2" :messages="$errors->get('phone')" />
                                </div>
                                <!-- secondary phone -->
                                <div class="col-6">
                                    <x-input-label for="secondary_phone" :value="__('taxpayers.secondary_phone')" />
                                    <x-text-input id="secondary_phone" name="secondary_phone" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->secondary_phone : (old('secondary_phone') ?? '')"
                                         autofocus autocomplete="secondary_phone" />
                                    <x-input-error class="mt-2" :messages="$errors->get('secondary_phone')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- email -->
                                <div>
                                    <x-input-label for="email" :value="__('Email')" />
                                    <x-text-input id="email" name="email" type="email" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->email : (old('email') ?? '')"
                                         required autocomplete="username" />
                                    <x-input-error class="mt-2" :messages="$errors->get('email')" />
                                </div>
                            </div>

                            <div class="row">
                                <div class="flex items-center gap-4 justify-content-end">
                                    <x-secondary-button onclick="history.back()" class="bg-light">
                                        {{ __('Cancel') }}
                                    </x-secondary-button>

                                    @if(!(isset($read_only) && $read_only))
                                    <x-primary-button>
                                        @if (isset($taxpayer))
                                        {{ __('Update') }}
                                        @else
                                        {{ __('Save') }}
                                        @endif
                                    </x-primary-button>
                                    @endif

                                    @if (session('status') === 'profile-updated')
                                    <p x-data="{ show: true }" x-show="show" x-transition
                                        x-init="setTimeout(() => show = false, 2000)"
                                        class="text-sm text-gray-600 dark:text-gray-400">{{ __('Saved.') }}</p>
                                    @endif
                                </div>
                            </div>

                        </form>
                </div>
            </div>
        </div>
    </section>

    <x-slot name="script">
        @include('taxpayers.scripts-form')
    </x-slot>

</x-app-layout>

resources/views/taxpayers/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            {{ __('taxpayers.taxpayers') }}
        </h2>
    </x-slot>
    <section>
        <div class="py-12">
            <div class=" pt-3 max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <div class="p-4 sm:p-8 bg-primary text-white shadow sm:rounded-lg">
                    <header>
                        <h2 class="text-lg font-medium text-white">
                            {{ __('taxpayers.taxpayers') }}
                        </h2>
                    </header>

                    @can('create taxpayer')
                    <div class="d-flex justify-content-end">
                        <x-link-button href="{{ route('taxpayer.create') }}">
                            {{ __('Add') }}
                        </x-link-button>
                    </div>
                    @endcan

                    <div class="py-6">
                        <input type="hidden" id="role" value="{{ Auth::user()->getRoleNames() }}" >
                        <hr>
                        <table id="taxpayersTable" class="table table-striped table-secondary" style="width:100%">
                            <thead>
                                <tr>
                                    <th> {{__('taxpayers.docType')}} </th>
                                    <th> {{__('taxpayers.docNumber')}} </th>
                                    <th> {{__('taxpayers.names')}} </th>
                                    <th> {{__('taxpayers.lastnames')}} </th>
                                    <th> {{__('taxpayers.phone')}} </th>
                                    <th> {{__('Actions')}} </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($taxpayers as $taxpayer)
                                <tr>
                                    <td> {{ $taxpayer->documentType->name }} </td>
                                    <td> {{ $taxpayer->doc_number }} </td>
                                    <td> {{ $taxpayer->names }} </td>
                                    <td> {{ $taxpayer->lastnames }} </td>
                                    <td> {{ $taxpayer->phone}} </td>
                                    <td>
                                        <div class="d-flex justify-content-between align-items-center">
                                            @can('view taxpayer')
                                            <x-link-button href="{{ route('taxpayer.show', $taxpayer->id ) }}" class="pl-2">
                                                <x-see-svg/>                                          
                                            </x-link-button>
                                            @endcan
                                            @can('edit taxpayer')
                                            <x-link-button href="{{ route('taxpayer.edit', $taxpayer->id ) }}" class="pl-2">
                                                <x-edit-svg/>                                          
                                            </x-link-button>
                                            @endcan
                                            @can('delete taxpayer')
                                            <div class="btn p-0">
                                                <form method="POST"
                                                    action="{{ route('taxpayer.destroy', ['taxpayer' => $taxpayer]) }}"
                                                    class=""
                                                >
                                                    @csrf 
                                                    @method('DELETE')  
                                                    <x-danger-button type="submit">
                                                        <x-delete-svg/>
                                                    </x-danger-button>
                                                </form>
                                            </div>
                                            @endcan
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th> {{__('taxpayers.docType')}} </th>
                                    <th> {{__('taxpayers.docNumber')}} </th>
                                    <th> {{__('taxpayers.names')}} </th>
                                    <th> {{__('taxpayers.lastnames')}} </th>
                                    <th> {{__('taxpayers.phone')}} </th>
                                    <th> Actions </th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>


    <x-slot name="script">
        @include('taxpayers.scripts-list')
    </x-slot>
</x-app-layout>

resources/views/taxpayers/scripts-form.blade.php
<script>

    const docType = document.getElementById('doc_type');
    const readOnly = document.getElementById('read_only');

    docType.addEventListener('change', (event) => {
        const selectedOption = event.target.value;
        console.log('Selected option:', selectedOption);

        if (docType.value === 'NIT') {
            console.log('se seleccionó NIT');
        }
    })



</script>

<script type="module">

    $(document).ready(function () {
        if ($('#read_only').val() == true) {
            $('select').prop('disabled', true);
            $('input').prop('disabled', true);
        }
        console.log($("#doc_type").val());
        if ($("#doc_type").val() === "NIT") {
            $('#label_names').text("{{__('taxpayers.business_name')}}")
            $('#names_div').removeClass('col-6');
            $('#names_div').addClass('col-12');

            if ($('#lastnames').val() != '') {
                $('#names').val($('#names').val() + ' ' + $('#lastnames').val());
            }

            $('#lastnames').hide();
            $('#label_lastnames').hide();
        }
    });

    $("#doc_type").change(function () {
        var docType = $(this).val();

        if (docType === "NIT") {
            $('#label_names').text("{{__('taxpayers.business_name')}}")
            $('#names_div').removeClass('col-6');
            $('#names_div').addClass('col-12');
            $('#lastnames').hide();
            $('#label_lastnames').hide();
        } else {
            $('#label_names').text("{{__('taxpayers.names')}}")
            $('#names_div').addClass('col-6');
            $('#names_div').removeClass('col-12');
            $('#lastnames').show();
            $('#label_lastnames').show();
        }
    });

</script>