routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use App\Http\Controllers\RolesController;
use App\Http\Controllers\TaxpayerController;
use App\Http\Controllers\DocumentTypeController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('welcome');
})->name('welcome');


Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

/* Route::group(['middleware' => ['auth:admin']], function () {
    // Rutas protegidas para el guardia 'admin'
}); */


Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');

    Route::resource('/user', RolesController::class)->except(['store', 'update']);
    Route::match(['post', 'put'], '/user', [RolesController::class, 'storeOrUpdate'])->name('user.storeOrUpdate');

    Route::resource('/taxpayer', TaxpayerController::class)->except(['store', 'update']);
    Route::match(['post', 'put'], '/taxpayer', [TaxpayerController::class, 'storeOrUpdate'])->name('taxpayer.storeOrUpdate');
    
    Route::resource('/document-type', DocumentTypeController::class);
});

require __DIR__.'/auth.php';

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/doc-type/form.blade.php
<dd>In progress</dd>

<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            {{ __('docTypes.docTypes') }} / {{ (isset($doctype)) ? __('Edit') : __('Add') }}
        </h2>
    </x-slot>
    <section>
        <div class="py-6">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <div class="p-4 sm:p-8 bg-primary text-white shadow sm:rounded-lg container">

                    <header>
                        <h2 class="text-lg font-medium">
                            {{ __('docTypes.info') }}
                        </h2>
                    </header>

                    @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                    @endif

                    <hr>

                    @if(isset($taxpayer))
                        <form action="{{ route('taxpayer.storeOrUpdate', ['taxpayer' =>$taxpayer]) }}" method="POST"
                            class="mt-6 space-y-6">
                            @method('PUT')
                            @csrf
                            <input type="hidden" name="id" value="{{$taxpayer->id}}">
                            <dd>{{ $taxpayer->id }}</dd>
                    @else
                        <form action="{{ route('taxpayer.storeOrUpdate') }}" method="POST" class="mt-6 space-y-6">
                            @method('POST')
                            @csrf
                    @endif
                            <input type="hidden" id="read_only" value="{{$read_only ?? 'false' }}">

                            <div class="row">
                                <!-- docType -->
                                <div class="col-6">
                                    <x-input-label for="doc_type" :value="__('docTypes.docType')" />
                                    <x-select-input :options="$doctype"
                                        :value="isset($taxpayer) ? $taxpayer->doc_type : (old('doc_type') ?? '')"
                                        id="doc_type" name="doc_type" class="mt-1 block w-full"
                                        required autofocus
                                        autocomplete="doc_type"></x-select-input>
                                </div>

                                <!-- docNumber -->
                                <div class="col-6">
                                    <x-input-label for="doc_number" :value="__('docTypes.docNumber')" />
                                    <x-text-input id="doc_number" name="doc_number" type="text"
                                        class="mt-1 block w-full @error('title') is-invalid @enderror"
                                        :value="isset($taxpayer) ? $taxpayer->doc_number : (old('doc_number') ?? '')"
                                         required autofocus autocomplete="doc_number" />
                                    <x-input-error class="mt-2" :messages="$errors->get('doc_number')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- names -->
                                <div class="col-6" id="names_div">
                                    <x-input-label for="name" id="label_names" :value="__('docTypes.names')" />
                                    <x-text-input id="names" name="names" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->names : (old('names') ?? '')"
                                        required autofocus autocomplete="names" />
                                    <x-input-error class="mt-2" :messages="$errors->get('names')" />
                                </div>

                                <!-- lastnames -->
                                <div class="col-6">
                                    <x-input-label for="lastnames" id="label_lastnames" :value="__('docTypes.lastnames')" />
                                    <x-text-input id="lastnames" name="lastnames" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->lastnames : (old('lastnames') ?? '')"
                                         autofocus autocomplete="lastnames" />
                                    <x-input-error class="mt-2" :messages="$errors->get('lastnames')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- address -->
                                <div class="col-12">
                                    <x-input-label for="address" :value="__('docTypes.address')" />
                                    <x-text-input id="address" name="address" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->address : (old('address') ?? '')" 
                                         required autofocus autocomplete="address" />
                                    <x-input-error class="mt-2" :messages="$errors->get('address')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- phone -->
                                <div class="col-6">
                                    <x-input-label for="phone" :value="__('docTypes.phone')" />
                                    <x-text-input id="phone" name="phone" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->phone : (old('phone') ?? '')"
                                         required autofocus autocomplete="phone" />
                                    <x-input-error class="mt-2" :messages="$errors->get('phone')" />
                                </div>
                                <!-- secondary phone -->
                                <div class="col-6">
                                    <x-input-label for="secondary_phone" :value="__('docTypes.secondary_phone')" />
                                    <x-text-input id="secondary_phone" name="secondary_phone" type="text" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->secondary_phone : (old('secondary_phone') ?? '')"
                                         autofocus autocomplete="secondary_phone" />
                                    <x-input-error class="mt-2" :messages="$errors->get('secondary_phone')" />
                                </div>
                            </div>

                            <div class="row">
                                <!-- email -->
                                <div>
                                    <x-input-label for="email" :value="__('Email')" />
                                    <x-text-input id="email" name="email" type="email" class="mt-1 block w-full"
                                        :value="isset($taxpayer) ? $taxpayer->email : (old('email') ?? '')"
                                         required autocomplete="username" />
                                    <x-input-error class="mt-2" :messages="$errors->get('email')" />
                                </div>
                            </div>

                            <div class="row">
                                <div class="flex items-center gap-4 justify-content-end">
                                    <x-secondary-button onclick="history.back()" class="bg-light">
                                        {{ __('Cancel') }}
                                    </x-secondary-button>

                                    @if(!(isset($read_only) && $read_only))
                                    <x-primary-button>
                                        @if (isset($taxpayer))
                                        {{ __('Update') }}
                                        @else
                                        {{ __('Save') }}
                                        @endif
                                    </x-primary-button>
                                    @endif

                                    @if (session('status') === 'profile-updated')
                                    <p x-data="{ show: true }" x-show="show" x-transition
                                        x-init="setTimeout(() => show = false, 2000)"
                                        class="text-sm text-gray-600 dark:text-gray-400">{{ __('Saved.') }}</p>
                                    @endif
                                </div>
                            </div>

                        </form>
                </div>
            </div>
        </div>
    </section>

    <x-slot name="script">
        @include('doc-types.scripts-form')
    </x-slot>

</x-app-layout>

resources/views/doc-type/list.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl leading-tight">
            {{ __('docTypes.docTypes') }} / {{ (isset($docType)) ? __('Edit') : __('Add') }}
        </h2>
    </x-slot>
    <section>
        <div class="py-6">
            <div class="max-w-7xl mx-auto sm:px-6 lg:px-8 space-y-6">
                <div class="p-4 sm:p-8 bg-primary text-white shadow sm:rounded-lg container">
                    <header>
                        <h2 class="text-lg font-medium text-white">
                            {{ __('docTypes.info') }}
                        </h2>
                    </header>
                    
                    @can('create doctype')
                    <div class="d-flex justify-content-end">
                        <x-link-button href="{{ route('taxpayer.create') }}">
                            {{ __('Add') }}
                        </x-link-button>
                    </div>
                    @endcan

                    <hr>
                    
                    <div class="py-6">
                    <input type="hidden" id="role" value="{{ Auth::user()->getRoleNames() }}" >

                        <table id="docTypesTable" class="table table-striped table-secondary" style="width:100%">
                            <thead>
                                <tr>
                                    <th> {{__('docTypes.id')}} </th>
                                    <th> {{__('docTypes.short_name')}} </th>
                                    <th> {{__('docTypes.name')}} </th>
                                    <th> {{__('Actions')}} </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($documentTypes as $docType)
                                <tr>
                                    <td> {{ $docType->id }} </td>
                                    <td> {{ $docType->short_name }} </td>
                                    <td> {{ $docType->name }} </td>
                                    <td>
                                        <div class="d-flex justify-content-between align-items-center">

                                            @can('view doctype')
                                            <x-link-button href="{{ route('document-type.show', $docType->id ) }}" class="pl-2">
                                                <x-see-svg/>                                          
                                            </x-link-button>
                                            @endcan

                                            @can('edit doctype')
                                            <x-link-button href="{{ route('document-type.edit', $docType->id ) }}">
                                                <x-edit-svg/>                                          
                                            </x-link-button>
                                            @endcan

                                            @can('delete doctype')
                                            <form method="POST" 
                                                action="{{ route('document-type.destroy', ['document_type' => $docType]) }}"
                                                class="ml-2"
                                            >
                                                @csrf 
                                                @method('DELETE')  
                                                <x-danger-button type="submit">
                                                    <x-delete-svg/>
                                                </x-danger-button>
                                            </form>
                                            @endcan
                                        </div>                                          
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <x-slot name="script">
        @include('doc-type.scripts-list')
    </x-slot>
</x-app-layout>

resources/views/doc-type/scripts-list.blade.php
<script type="module">
    $('#docTypesTable').DataTable({
        language,
        columns: [
            { width: '20%' },
            { width: '20%' },
            { width: '40%' },
            { width: '20%', visible: (($('#role').val() !== '["SuperAdmin"]' ) ? false : true) }
        ],
    });
</script>